// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;

using MoPhoGames.USpeak.Interface;


public class PhotonVoiceSender : MonoBehaviour, ISpeechDataHandler
{
	USpeaker spk;

	void Start() {
		spk = USpeaker.Get (this);
		if (networkView.isMine) {
			spk.SpeakerMode = SpeakerMode.Local;
		}else{
			spk.SpeakerMode = SpeakerMode.Remote;
		}

	}

	#region ISpeechDataHandler Members

	public void USpeakOnSerializeAudio( byte[] data ){
		networkView.RPC ("vc", RPCMode.All, data);
	}

	public void USpeakInitializeSettings( int data ){
		networkView.RPC ("init", RPCMode.All, data);
	}

	#endregion

	[RPC]
	void init( int data ){
		spk.InitializeSettings (data);
	}

	[RPC]
	void vc( byte[] data ){
		spk.ReceiveAudio (data);
	}

}

