// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;

using MoPhoGames.USpeak.Interface;


public class VoiceSender : MonoBehaviour, ISpeechDataHandler
{
	USpeaker spk;
	private Light otherPlayerLight;
	private Light myLight;
	private const float MY_SENSITIVITY = .1f;
	private const float MIN_LIGHT_DECREASE = 1.0f;
	private const float MAX_LIGHT_INTENSITY = 2.0f;
	private const float LOUD_TO_RANGE_RATIO = 20.0f;
	private float loudness = 0;

	void Start() {
		spk = USpeaker.Get (this);
		this.tag = null;
		if (networkView.isMine) {
			gameObject.AddComponent<AudioListener> ();
			spk.SpeakerMode = SpeakerMode.Local;
		}else{
			spk.SpeakerMode = SpeakerMode.Remote;
		}
		myLight = gameObject.GetComponent<Light> ();

	}

	#region ISpeechDataHandler Members

	public void USpeakOnSerializeAudio( byte[] data ){
		networkView.RPC ("vc", RPCMode.All, data);
	}

	public void USpeakInitializeSettings( int data ){
		networkView.RPC ("init", RPCMode.All, data);
	}

	#endregion

	[RPC]
	void init( int data ){
		spk.InitializeSettings (data);
	}

	[RPC]
	void vc( byte[] data ){
		spk.ReceiveAudio (data);
	}

	public float GetAverage(byte[] data){
		int a = 0;
		
		foreach (byte s in data) {
			a += s;
		}
		
		return (float)a / data.Length;
	}

	//Set the other player's camera
	private void SetOtherPlayerLight() {
		if (otherPlayerLight == null) {
			otherPlayerLight = GameObject.FindGameObjectWithTag ("Player").GetComponent<Light>();
		}
	}

}

